import Head from 'next/head'

import InputBox from '../components/InputBox'

export default function Home() {
  return (
    <div className="min-h-screen bg-indigo-50">
      <Head>
        <title>Permission Simulator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-6">
        <header className="mb-6">
          <h1 className="mb-2 text-3xl font-bold">Permission Simulator</h1>
          <p>
            Permission Simulator は Linux
            で扱われるファイルの権限管理のシミュレーターです。
          </p>
        </header>

        <main className="flex">
          <div>
            <InputBox type="file" />
          </div>
          <div className="ml-4">
            <InputBox type="read" />
            <InputBox type="write" />
            <InputBox type="execute" />
          </div>
          <div className="ml-4">
            <InputBox type="read" />
            <InputBox type="write" />
            <InputBox type="execute" />
          </div>
          <div className="ml-4">
            <InputBox type="read" />
            <InputBox type="write" />
            <InputBox type="execute" />
          </div>
        </main>
      </div>
    </div>
  )
}
