import clsx from 'clsx'
import Head from 'next/head'
import { useState } from 'react'

export default function Home() {
  const [text, setText] = useState('')

  return (
    <div className="min-h-screen bg-indigo-50">
      <Head>
        <title>Permission Simulator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-6">
        <header className="mb-6">
          <h1 className="mb-2 text-3xl font-bold">Permission Simulator</h1>
          <p>
            Permission
            SimulatorはLinuxで扱われるファイルの権限管理のシミュレーターです。
          </p>
        </header>

        <main>
          <p className="h-12">{text}</p>
          <div>
            <input
              onChange={e => setText(e.target.value)}
              maxLength={1}
              className={clsx([
                text === ''
                  ? 'border-2 border-indigo-100 border-dashed'
                  : 'border-2 border-indigo-600',
                'w-12',
                'h-12',
                'text-center',
                'text-xl',
              ])}
            ></input>
          </div>
        </main>
      </div>
    </div>
  )
}
